-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS mehedih3_cpro306_g10;
USE mehedih3_cpro306_g10;

-- CUSTOMER Table
CREATE TABLE IF NOT EXISTS CUSTOMER (
    CustomerID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Phone VARCHAR(20),
    Address TEXT,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RESTAURANT Table
CREATE TABLE IF NOT EXISTS RESTAURANT (
    RestaurantID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Address TEXT,
    CuisineType VARCHAR(100),
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    ImageURL VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DELIVERY_PARTNER Table
CREATE TABLE IF NOT EXISTS DELIVERY_PARTNER (
    PartnerID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(20),
    VehicleDetails VARCHAR(100),
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- MENU_ITEM Table
CREATE TABLE IF NOT EXISTS MENU_ITEM (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    RestaurantID INT NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Category VARCHAR(50),
    ImageURL VARCHAR(255),
    FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE
);

-- PAYMENT Table
CREATE TABLE IF NOT EXISTS PAYMENT (
    PaymentID INT AUTO_INCREMENT PRIMARY KEY,
    Method VARCHAR(50),
    Status VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ORDER Table
CREATE TABLE IF NOT EXISTS `ORDER` (
    OrderID INT AUTO_INCREMENT PRIMARY KEY,
    CustomerID INT NOT NULL,
    RestaurantID INT NOT NULL,
    PartnerID INT,
    PaymentID INT,
    Status VARCHAR(50) DEFAULT 'Pending',
    TotalAmount DECIMAL(10, 2) NOT NULL,
    OrderTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE,
    FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    FOREIGN KEY (PartnerID) REFERENCES DELIVERY_PARTNER(PartnerID) ON DELETE SET NULL,
    FOREIGN KEY (PaymentID) REFERENCES PAYMENT(PaymentID) ON DELETE SET NULL
);

-- ORDER_ITEM Table
CREATE TABLE IF NOT EXISTS ORDER_ITEM (
    OrderItemID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT NOT NULL,
    ItemID INT NOT NULL,
    Quantity INT NOT NULL,
    Subtotal DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES `ORDER`(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES MENU_ITEM(ItemID) ON DELETE CASCADE
);

-- ADMIN Table
CREATE TABLE IF NOT EXISTS ADMIN (
    AdminID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL
);
-- PASSWORD_RESET Table
CREATE TABLE IF NOT EXISTS PASSWORD_RESET (
    ResetID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(100) NOT NULL,
    Token VARCHAR(64) NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    Used BOOLEAN DEFAULT FALSE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX (Token),
    INDEX (Email)
);

-- REVIEW Table
CREATE TABLE IF NOT EXISTS REVIEW (
    ReviewID INT AUTO_INCREMENT PRIMARY KEY,
    CustomerID INT NOT NULL,
    RestaurantID INT,
    PartnerID INT,
    Rating INT NOT NULL CHECK (Rating >= 1 AND Rating <= 5),
    Comment TEXT,
    Status VARCHAR(50) DEFAULT 'Pending',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE,
    FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE,
    FOREIGN KEY (PartnerID) REFERENCES DELIVERY_PARTNER(PartnerID) ON DELETE CASCADE
);

-- COUPON Table
CREATE TABLE IF NOT EXISTS COUPON (
    CouponID INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    RestaurantID INT,
    DiscountType VARCHAR(20) NOT NULL,
    DiscountValue DECIMAL(10, 2) NOT NULL,
    ExpiryDate DATETIME,
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE
);
